language: php

php:
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer --prefer-source install
